#!/bin/bash

# Created by Shivani Bhardwaj <shivanib134@gmail.com>

# Description
# ------------
# This script will take the logs generated by running the check
# and write to the console about the processes that are unreliable

# Scope
# -----
# This script is fully functional and leaves no scope of change

RED='\033[0;31m'
NC='\033[0m'
GRN='\033[1;32m'

while IFS='' read -r l || [[ -n read "$l" ]]; do
	echo "${RED}WARNING Message"
	echo "------------------"
	echo "${NC}Process ${RED}$l ${NC}is unidentifiable and suspicious."
	echo "If the process is ${GRN}OK${NC}, consider updating your dictionary."
	echo "Else, kill the process and delete its binary."
	echo
done < log
